version: "3.9"
services:
  bot:
    container_name: bot
    build: ./bot
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    networks:
      - bot_network

  db:
    container_name: postgres
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data_db:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - bot_network

volumes:
  data_db:

networks:
  bot_network:
    driver: bridge
